import os
import google.generativeai as genai
from django.conf import settings

# Configure the AI
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

def generate_medical_summary(patient_data):
    """
    Sends patient data to Gemini and returns a professional medical summary.
    """
    
    # 1. Select the CORRECT Model from your list
    # We are using the stable 2.0 Flash model you have access to
    model = genai.GenerativeModel('gemini-2.0-flash')

    # 2. System Prompt
    system_instruction = """
    You are GemmaCare, an advanced medical AI assistant.
    Your goal is to summarize patient records for a doctor.
    
    RULES:
    1. Be concise and professional.
    2. Highlight critical risks (allergies, drug interactions).
    3. MANDATORY DISCLAIMER: End with "Generated by AI. Verify with clinical judgment."
    """

    # 3. User Prompt
    user_prompt = f"""
    Please analyze this patient record:
    - Name: {patient_data['name']}
    - Age: {patient_data['age']}
    - Medical History: {patient_data['history']}
    - Current Medications: {patient_data['meds']}
    - Allergies: {patient_data['allergies']}
    
    Provide a clinical summary and risk assessment.
    """

    # 4. Generate
    try:
        response = model.generate_content(system_instruction + "\n\n" + user_prompt)
        return response.text
    except Exception as e:
        return f"⚠️ AI Service Unavailable: {str(e)}"
